### PR TITLE
The update that changed the world

### PR DESCRIPTION
**Pull request by Chocohead**
Switch over to [(provisional) Intermediaries](https://gist.github.com/Chocohead/b7ea04058776495a93ed2d13f34d697a). I don't think they'll change again now but I'll play it safe for now.

Whilst it is a lot of changes I've scanned over and everything looks right. Argo is completely dropped from being mapped as it is done at the Intermediary stage now. Inner/nested classes are also determined at the Intermediary stage, but aren't named so that's where they will have come from. It might be worth double checking some of the names (especially for the now nested classes) as they might be overly verbose now.

~~I'll see what I can do with the `build.gradle` to get it loading like normal Yarn does without having to do some of the hard parts manually.~~ All hooked back up so running `yarn` should work as well as it does on the normal Yarn repo. Didn't try exporting to see if it works either way, but equally it's no fun if I do absolutely everything :P

### CODE REVIEW

**Comment by Blayyke** [comment]
I haven't had too good a look into the gradle stuff, but all of the mappings file changes seem fine to me aside from maybe the inner classes having packages different to those of the parent.

**Comment by Chocohead** [comment]
All the inner classes should be fixed/sorted out now. Just over a dozen classes I originally said were anonymous have been switched to just being inner classes as they look suspiciously public to actually be anonymous. There's collateral from surrounding class numbers switching around but given they were alright before they will be now too.

I dare say this is ready to merge now.

**Comment by Blayyke** [comment]
I cloned it locally and was able to start enigma, so all seems good to me. Any other input we need on this or should I just merge now?

**Comment by Chocohead** [comment]
Ultimately that's up to you as it's your mappings, but I don't see anything else to do now.

**Comment by Blayyke** [comment]
Don't know who else to bother, so seems good to me.

**Pull request merged**
